export const text = {
  appName: "Write More",
  notes: {
    header: "Notes",
    notesForm: {
      titleNew: "New Note",
      titleEdit: "Edit Note",
      titleUnknown: "Unknown Note",
      buttons: {
        submit: "Submit",
        cancel: "Cancel",
      },
      helperText: {
        nameRequired: "Name is required",
        contentRequired: "Content is required",
        urlValid: "Please enter a valid URL",
      },
      links: {
        name: "Link name",
        url: "Link URL",
        addLink: "Add Link",
      },
    },
    noteItem: {
      created: "Created",
      updated: "Updated",
      comments: {
        title: "Comment",
        add: "Add comment",
        loading: "Loading comments...",
        empty: "No comments yet",
        placeholder: "Write a comment",
        submit: "Comment",
        error: "Failed to load comments",
        edited: "Edited",
        edit: "Edit",
        delete: "Delete",
        save: "Save",
        cancel: "Cancel",
      },
    },
    notesList: {
      loading: "Loading notes",
      noNotes: "Create a new note to get started!",
      createNote: "Create Note",
      fetchError: "Failed to load notes. Please try again.",
      createTodo: "Create Todo",
      noNotesAvailable: "No notes available.",
    },
    noteDetail: {
      loading: "Loading...",
      notFound: "Note not found",
    },
    deleteNote: {
      title: "Delete Note",
      titleUnknown: "Unknown Note",
      confirmation:
        "Are you sure you want to delete '{title}'? This action cannot be undone.",
      buttons: { confirm: "Delete", cancel: "Cancel" },
    },
  },
  todos: {
    header: "Todos",
    todosForm: {
      titleNew: "New Todo",
      titleEdit: "Edit Todo",
      titleUnknown: "Unknown Todo",
      buttons: {
        submit: "Submit",
        cancel: "Cancel",
      },
      helperText: {
        nameRequired: "Name is required",
      },
    },
    todosList: {
      loading: "Loading todos",
      noTodos: "Create a new todo to get started!",
      createTodo: "Create Todo",
      fetchError: "Failed to load todos. Please try again.",
      noTodosAvailable: "No todos available.",
    },
    todoDetail: {
      loading: "Loading...",
      notFound: "Todo not found",
    },
    deleteTodo: {
      title: "Delete Todo",
      titleUnknown: "Unknown Todo",
      confirmation:
        "Are you sure you want to delete '{title}'? This action cannot be undone.",
      buttons: { confirm: "Delete", cancel: "Cancel" },
    },
  },
  trips: {
    header: "Trips",
    tripsForm: {
      titleNew: "New Trip",
      titleEdit: "Edit Trip",
      titleUnknown: "Unknown Trip",
      buttons: {
        submit: "Submit",
        cancel: "Cancel",
      },
      helperText: {
        titleRequired: "Title is required",
      },
    },
    deleteTrip: {
      title: "Delete Trip",
      titleUnknown: "Unknown Trip",
      confirmation:
        "Are you sure you want to delete '{title}'? This action cannot be undone.",
      buttons: { confirm: "Delete", cancel: "Cancel" },
    },
    tripsList: {
      loading: "Loading trips",
      noTrips: "Create a new trip to get started!",
      createTrip: "Create Trip",
      fetchError: "Failed to load trips. Please try again.",
    },
    tripDetail: {
      loading: "Loading trip",
      notFound: "Trip not found",
      imagesHeader: "Images",
      noImages: "No images uploaded yet.",
      loadingImages: "Loading images...",
      imageFetchError: "Failed to load images.",
      openGallery: "Open image gallery",
    },
    imageUpload: {
      title: "Upload Image",
      helperText:
        "Select an image to upload. It will be compressed automatically.",
      buttons: {
        chooseFile: "Choose Image",
        noFileSelected: "No file selected",
        upload: "Upload",
        uploading: "Uploading...",
        cancel: "Cancel",
      },
      errors: {
        noFile: "Please choose a file first.",
        uploadFailed: "Failed to upload image. Please try again.",
      },
    },
    imageSlideshow: {
      previous: "Previous image",
      next: "Next image",
      close: "Close gallery",
      delete: "Delete image",
      fallbackAlt: "Trip image",
    },
    addUser: {
      title: "Add User to Trip",
      loading: "Loading users...",
      noUsers: "No users found.",
      fetchError: "Failed to load users.",
      close: "Close",
    },
  },
  users: {
    header: "Users",
  },
  footer: {
    header: "Write More travel app",
    github: "Github b3rg3t",
    linkedin: "LinkedIn profile",
    linkedinUrl: "https://www.linkedin.com/in/david-berg-385530175/",
    githubUrl: "https://github.com/b3rg3t",
    madeBy: "Made with ♥ by David Berg.",
    about: "About",
  },
  user: {
    header: "Users",
    form: {
      title: "Create New User",
      username: "Username",
      email: "Email",
      password: "Password",
      cancel: "Cancel",
      create: "Create",
      error: "Failed to create user",
      helperText: {
        usernameRequired: "Username is required",
        emailRequired: "Email is required",
        passwordRequired: "Password is required",
      },
      buttons: {
        submit: "Submit",
      },
    },
    usersList: {
      loading: "Loading users...",
      noUsers: "No users found",
      createUser: "Create a new user",
      fetchError: "Failed to fetch users",
    },
    signin: {
      title: "Sign In",
      email: "Email",
      password: "Password",
      submit: "Sign In",
      submitting: "Signing in...",
      switchToSignup: "Don't have an account? Sign up",
      error: "Failed to sign in. Please try again.",
      helperText: {
        emailRequired: "Email is required",
        passwordRequired: "Password is required",
      },
    },
    signup: {
      title: "Sign Up",
      username: "Username",
      email: "Email",
      password: "Password",
      firstName: "First Name",
      lastName: "Last Name",
      submit: "Sign Up",
      submitting: "Creating account...",
      switchToSignin: "Already have an account? Sign in",
      error: "Failed to sign up. Please try again.",
      helperText: {
        usernameRequired: "Username is required",
        emailRequired: "Email is required",
        passwordRequired: "Password is required (min 6 characters)",
      },
    },
    profile: {
      title: "Update Profile",
      open: "Open profile",
      username: "Username",
      firstName: "First name",
      lastName: "Last name",
      password: "New password",
      edit: "Edit user",
      cancelEdit: "Cancel",
      submit: "Save Changes",
      saving: "Saving...",
      success: "Profile updated successfully",
      error: "Failed to update profile. Please try again.",
      helperText: {
        passwordMin: "Password must be at least 6 characters",
      },
    },
  },
  updatePrompt: {
    message: "A new version is available.",
    reload: "Reload",
    dismiss: "Dismiss",
  },
  errors: {
    root: "An error occurred",
  },
} as const;
